[project]
name = "2026-sd-3a"
version = "0.1.0"
description = "-"
readme = "README.md"
requires-python = ">=3.12"
license = { text = "MIT" }
authors = [
    { name = "Muhammad Affandes", email = "affandes@uin-suska.ac.id" }
]

[project.optional-dependencies]
dev = [
    "pytest>=8.0",
]

[tool.pytest.ini_options]
testpaths = ["test"]